### PR TITLE
[local-hypertable] Fix infinite loop when inserting into a table cont…

### PR DESCRIPTION
**Pull request by neboat**
…aining only a run of tombstones and keys with smaller hashes.

### CODE REVIEW

**Comment by VoxSciurorum** [comment]
The diff adds two comparisons between `tgt` and `next_i`.   The test exercises the second one only.  If I take out the new loop termination condition `next_i != tgt` the test still passes.

**Comment by neboat** [comment]
I updated the tests to check both comparisons.

I also fixed one other insertion case that requires a tombstone to be moved.  I haven't encountered this case in any microbenchmark or application tests, but I can construct a table where it might occur, which is what the test for this case does.

**Comment by neboat** [comment]
I found a way to simplify the local-hypertable logic, using a very simple bit trick to avoid cases, conditional checks, and redundant code.  I also improved the unit testing for this hypertable implementation.

**Comment by VoxSciurorum** [comment]
I don't like the `hash()` function.  It has the illusion of portability but is designed for 64 bits of input yielding 32 bits of output.  It should have a comment saying "this is only valid for LP64" or some thought should be given to other sizes.

You could add the SplitMix code for the case where both input and output are the same.
```
    if (sizeof (uintptr_t) == sizeof (index_t)) {
        const int shift = 4 * sizeof (uintptr_t) + 1;
        // mix64 from SplitMix.
        x = (x ^ (x >> shift)) * 0xff51afd7ed558ccdUL;
        x = (x ^ (x >> shift)) * 0xc4ceb9fe1a85ec53UL;
        return x ^ (x >> shift);
    }
```

There is an extra word in a comment in local-hypertable.c: "Otherwise this entry contains have another valid"

**Comment by neboat** [comment]
The previous mixing function contained bugs, some of which are still present in the version you propose.  Rather than make the code more complex by fixing those specific bugs, for this PR, I chose a hash function, based on abseil's, that is simpler and still effective for hypertables as they are today, i.e., with 32-bit indices.  The existing comment in the code already clarifies that the hash function yields 32-bit outputs from 64-bit inputs.

We can evaluate the need to support hypertables with larger indices in a later PR.  There are variants of abseil's low-level hash function for other sizes, including variants to produce 64-bit outputs from 64-bit inputs.  But those variants introduce additional code complexity that is not necessary to fix the current issues with hypertables.

**Pull request merged**
